### ISSUE TITLE
【分享】golang channel 详解

### ISSUE THREAD

**Issue by lixianyang** [cloudnativeto/sig-kubernetes#28]
## 分享内容

大家在看 k8s 源码的时候不免会看到不少 channel 相关的操作。在GopherCon 2017中，Golang专家Kavya深入介绍了 Go Channels 的内部机制，以及运行时调度器和内存管理系统是如何支持Channel的，图文并茂，简单直观，有时间的小伙伴可以看看。

[文档链接](https://github.com/gophercon/2017-talks/blob/master/KavyaJoshi-UnderstandingChannels/Kavya%20Joshi%20-%20Understanding%20Channels.pdf)

**Comment by vincenthcui** [comment]
学习了，作者画图功力一流，通俗易懂
