### ISSUE TITLE
【提问】Reflector.lastSyncResourceVersion 是哪个资源的 resourceVersion

### ISSUE THREAD

**Issue by lixianyang** [cloudnativeto/sig-kubernetes#34]
## 问题描述

Reflector.ListAndWatch 方法中 resourceVersion 相关代码如下：

```golang
// List 部分代码
var resourceVersion string
options := metav1.ListOptions{ResourceVersion: "0"}
list, err = r.listerWatcher.List(options)
listMetaInterface, err := meta.ListAccessor(list)
resourceVersion = listMetaInterface.GetResourceVersion()
r.setLastSyncResourceVersion(resourceVersion)
// Watch 部分代码
		options = metav1.ListOptions{
			ResourceVersion: resourceVersion,
			// We want to avoid situations of hanging watchers. Stop any wachers that do not
			// receive any events within the timeout window.
			TimeoutSeconds: &timeoutSeconds,
		}
                w, err := r.listerWatcher.Watch(options)
                err := r.watchHandler(w, &resourceVersion, resyncerrc, stopCh)
```

watch 处理的逻辑在 watchHandler 函数，如下：

```golang
event, ok := <-w.ResultChan()
meta, err := meta.Accessor(event.Object)
newResourceVersion := meta.GetResourceVersion()
*resourceVersion = newResourceVersion
r.setLastSyncResourceVersion(newResourceVersion)
```

开始 List 后 resourceVersion 获取的是列表的资源版本 ```resourceVersion = listMetaInterface.GetResourceVersion()```
列表的资源版本是空值（这里有疑问，懂的同学解释一下）
Watch 的时候 resourceVersion 传入空值表示 [Get State and Start at Most Recent](https://kubernetes.io/docs/reference/using-api/api-concepts/#the-resourceversion-parameter)。
在 watchHandler 里根据最新资源的版本更新 resourceVersion，这样后续的 Watch 就会根据最新的资源版本监听。 Watch resourceVersion="{value other than 0}" 表示 [Start at Exact](https://kubernetes.io/docs/reference/using-api/api-concepts/#the-resourceversion-parameter)

这里理解的核心在于 Watch 调用对 resourceVersion 的处理。

一般觉得每个资源都会有 resourceVersion，那 Reflector 里一个 resourceVersion 怎么会够用，而且这个值一会儿是 List 的，一会儿是具体资源的。。。

**Comment by xyz-li** [comment]
1. List 获取的resourceVersion是etcd当前最大的 version
2. Watch获取的resourceVersion是当前资源发生改变的 ModRevision

在List完成之后会将最新的 resourceVersion传给 Watch, 这样就可以获取接口所关注资源的最新变化。
Reflector的resourceVersion一个就够了，因为它的用处是在ListWatch发生错误时， 下一次的ListWatch会根据之前设置的resourceVersion来ListWatch, 避免从0 ListWatch。加快速度， 减少数据请求量。
